// <auto-generated />
using System;
using BibliotecaApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotecaApi.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20260224235051_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("BibliotecaApi.Models.Agendamento", b =>
                {
                    b.Property<int>("IdAgendamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAgendamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataEmprestimo")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdAluno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdLivro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdAgendamento");

                    b.HasIndex("IdAluno");

                    b.HasIndex("IdLivro");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("BibliotecaApi.Models.Aluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdAluno");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("BibliotecaApi.Models.Diretor", b =>
                {
                    b.Property<int>("IdDiretor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdDiretor");

                    b.ToTable("Diretores");

                    b.HasData(
                        new
                        {
                            IdDiretor = 1,
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "inahdabiblioteca2025@gmail.com",
                            Nome = "Administrador",
                            Senha = "$2y$10$U4UGWsCNc3MN0oq.nk0hsuQib1d4Vyhx6DH4GWgETLOMjN7ffs/hW"
                        },
                        new
                        {
                            IdDiretor = 2,
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sandraferreirasoares@prof.educacao.sp.gov.br",
                            Nome = "Sandra",
                            Senha = "$2y$10$A7Of.Wf0fULxFObwc48keeFE9vVlWxCtHKECLBJuIDBVydRYog8am"
                        },
                        new
                        {
                            IdDiretor = 3,
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "erikasuzuki@professor.educacao.sp.gov.br",
                            Nome = "Erika",
                            Senha = "$2y$10$g1M7JMtJYTQDNgu59TrrkOb94fRGKe3R2hU6PFJek0BcBRKVdJ6t2"
                        },
                        new
                        {
                            IdDiretor = 4,
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thiagovargas@professor.educacao.sp.gov.br",
                            Nome = "Thiago",
                            Senha = "$2y$10$vbZUL5RCZT/WGMBU8Tc5CuzQ1BYvM9z/LZoU9xcchmPNroVWQPtWG"
                        },
                        new
                        {
                            IdDiretor = 5,
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "raquelmena@professor.educacao.sp.gov.br",
                            Nome = "Raquel",
                            Senha = "$2y$10$HI/mX7ZKfYhaVPrknN8N8uRfAgqRQXudNPnIcoN3eFKtYYwkqTLGG"
                        },
                        new
                        {
                            IdDiretor = 6,
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "prisciladucci@professor.educacao.sp.gov.br",
                            Nome = "Priscila",
                            Senha = "$2y$10$1Pf.aVOy9dYijTH9ICXeNuyCTrEaD27Gs7oPP1khXZJFn1JQg2EcS"
                        },
                        new
                        {
                            IdDiretor = 7,
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Solange.oliveira11@servidor.educacao.sp.gov.br",
                            Nome = "Solange",
                            Senha = "$2y$10$5CIUiwxX/j2AXUo5QqwDNu9wM4PcfopHzBP4vu.Oxv27RYD3ohWU6"
                        });
                });

            modelBuilder.Entity("BibliotecaApi.Models.Livro", b =>
                {
                    b.Property<int>("IdLivro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Disciplina")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Indicacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdLivro");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("BibliotecaApi.Models.Agendamento", b =>
                {
                    b.HasOne("BibliotecaApi.Models.Aluno", "Aluno")
                        .WithMany("Agendamentos")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibliotecaApi.Models.Livro", "Livro")
                        .WithMany("Agendamentos")
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("BibliotecaApi.Models.Aluno", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("BibliotecaApi.Models.Livro", b =>
                {
                    b.Navigation("Agendamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
